import React, { Component } from 'react';

class Terms extends Component {
    render() {
        return (
            <div style={{ padding: "8vw", textAlign: "justify" }}>
                <h1>Terms Of Service</h1><p />
                Effective since September 17th 2021<p />
                Last Updated: September 27th 2021<p />
                Introduction<p />
                Welcome to the NFT on Demand website, owned and operated by Blankit, Inc. These Terms of Use (these “Terms”) govern your access to and use of the  NFT on Demand website; including without limitation the creation, purchase, sale, exchange, or modification of certain digital assets; our online and/or mobile services, and software provided on or in connection with those services (collectively, the “Service”).<p />
                This Service also allows you to sell and purchase Crypto Assets (as defined below) via auction (“Auction”). Detailed rules regarding the Auction process are available on this page, Rules. You may only participate in the Auction by linking your digital wallets on supported bridge extensions such as MetaMask (https://metamask.io/). MetaMask is an electronic wallet, which allows you to purchase, store, and engage in transactions using Ethereum cryptocurrency. Also could include different wallets allowed in the near future. Before putting up your unique digital asset for Auction or putting in an offer to purchase a unique digital asset from another user, we will ask you to download a supported electronic wallet extension, and connect and unlock your digital wallets with that extension. Once you submit an order to sell or purchase a unique digital asset, your order is passed on to the applicable extension, which completes the transaction on your behalf.<p />
                “Crypto Assets” refers to unique non-fungible tokens, implemented on the Ethereum blockchain (the “Ethereum Platform”) using smart contracts, including without limitation Ethmoji, CryptoKitties, CryptoCelebrities, CryptoPunks and others.<p />
                ALL TRANSACTIONS INITIATED THROUGH OUR SERVICE ARE FACILITATED AND RUN BY THIRD-PARTY ELECTRONIC WALLET EXTENSIONS, AND BY USING OUR SERVICES YOU AGREE THAT YOU ARE GOVERNED BY THE TERMS OF SERVICE AND PRIVACY POLICY FOR THE APPLICABLE EXTENSIONS. FOR METAMASK, THOSE TERMS ARE AVAILABLE AT (https://metamask.io/terms.html) AND (https://metamask.io/privacy.html)<p />
                NFT On Demand is a Platform. We are not a broker, Financial institution, or creditor. The services are an administrative platform only. NFT On Demand FACILITATES TRANSACTIONS between the buyer and seller in the auction but is not a party to party to any agreement between the buyer and seller of crypto assets or between users.<p />
                YOU BEAR FULL RESPONSIBILITY FOR VERIFYING THE IDENTITY, LEGITIMACY, AND AUTHENTICITY OF ASSETS YOU PURCHASE ON NFT On Demand. NOTWITHSTANDING INDICATORS AND MESSAGES THAT SUGGEST VERIFICATION, NFT On Demand MAKES NO CLAIMS ABOUT THE IDENTITY, LEGITIMACY, OR AUTHENTICITY OF ASSETS ON THE PLATFORM.<p />
                Because we have a growing number of services, we sometimes need to describe additional terms for specific services. Those additional terms and conditions, which are available with the relevant services, then become part of your agreement with us if you use those services.<p />
                THESE TERMS OF USE ARE IMPORTANT AND AFFECT YOUR LEGAL RIGHTS, SO PLEASE READ THEM CAREFULLY. WE WANT TO LET YOU KNOW THAT THE TERMS INCLUDE AN ARBITRATION AGREEMENT WHICH WILL, WITH LIMITED EXCEPTIONS, REQUIRE DISPUTES BETWEEN US TO BE SUBMITTED TO BINDING AND FINAL ARBITRATION. UNLESS YOU OPT OUT OF THE ARBITRATION AGREEMENT: (1) YOU WILL ONLY BE PERMITTED TO PURSUE CLAIMS AND SEEK RELIEF AGAINST US ON AN INDIVIDUAL BASIS, NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE ACTION OR PROCEEDING; AND (2) YOU ARE AGREEING TO MANDATORY INDIVIDUAL ARBITRATION FOR THE RESOLUTION OF DISPUTES AND WAIVING YOUR RIGHT TO A JURY TRIAL ON YOUR CLAIMS. PLEASE READ SECTION 15 CAREFULLY.<p />
                BY CLICKING ON THE “I ACCEPT” BUTTON, COMPLETING THE ACCOUNT REGISTRATION PROCESS, USING OUR SERVICES AND/OR PURCHASING CRYPTO ASSETS, YOU AGREE TO BE BOUND BY THESE TERMS AND ALL OF THE TERMS INCORPORATED HEREIN BY REFERENCE. If you do not agree to these Terms, you may not access or use the Service or purchase the Crypto Assets.<p />
                NFT on Demand reserves the right to change or modify these Terms at any time and in our sole discretion. If we make changes to these Terms, we will provide notice of such changes, such as by sending an email notification, providing notice through the Service or updating the “Last Updated” date at the beginning of these Terms. By continuing to access or use the Service, you confirm your acceptance of the revised Terms and all of the terms incorporated therein by reference. We encourage you to review the Terms frequently to ensure that you understand the terms and conditions that apply when you access or use the Service. If you do not agree to the revised Terms, you may not access or use the Service.<p />
                Privacy Policy Please refer to our Privacy Policy for information about how we collect, use and share personal information about you.<p />
                Account Registration and Communication Preferences<p />
                If you wish to participate in an Auction for Crypto Assets, you will need to register for an account on the Service (“Account”). By creating an Account, you agree to (a) provide accurate, current and complete Account information about yourself, (b) maintain and promptly update from time to time as necessary your Account information, (c) maintain the security of your password and accept all risks of unauthorized access to your Account and the information you provide to us, and (d) immediately notify us if you discover or otherwise suspect any security breaches related to the Service, or your Account. NFT on Demand will block multiple accounts of the same user. Also, you agree that you will not:<p />
                create another account if we’ve disabled one you had unless you have our written permission first;<p />
                buy, sell, rent or lease access to your Account or username unless you have our written permission first;<p />
                share your Account password with anyone; or<p />
                log in or try to log in to access the Service through unauthorized third party applications or clients.<p />
                NFT on Demand may require you to provide additional information and documents at the request of any competent authority or in case of application of any applicable law or regulation, including laws related to anti-laundering (legalization) of incomes obtained by criminal means, or for counteracting financing of terrorism. NFT on Demand may also require you to provide additional information and documents in cases where it has reasons to believe that:<p />
                Your Account is being used for money laundering or for any other illegal activity;<p />
                You have concealed or reported false identification information and other details; or<p />
                Transactions effected via your Account were effected in breach of these Terms.<p />
                In such cases, NFT on Demand, in its sole discretion, may pause or cancel your Auction transactions until such additional information and documents are reviewed by NFT on Demand and accepted as satisfying the requirements of applicable law. If you do not provide complete and accurate information and documents in response to such a request, NFT on Demand may refuse to provide the Content (defined in Section 4(A) below) to you.<p />
                By creating an Account, you consent to receive electronic communications from NFT on Demand (e.g., via email or by posting notices to the Service). These communications may include notices about your Account (e.g., password changes and other transactional information) and are part of your relationship with us. You agree that any notices, agreements, disclosures or other communications that we send to you electronically will satisfy any legal communication requirements, including, but not limited to, that such communications be in writing. You should maintain copies of electronic communications from us by printing a paper copy or saving an electronic copy. We may also send you promotional communications via email, including, but not limited to, newsletters, special offers, surveys and other news and information we think will be of interest to you. You may opt out of receiving these promotional emails at any time by following the unsubscribe instructions provided therein.<p />
                By submitting personal data through our Site or Services, you agree to the terms of our Privacy Policy and you expressly consent to the collection, use and disclosure of your personal data in accordance with the Privacy Policy. Also by accepting you are aware of the fee that NFT on Demand charges per transaction, you are also aware that the fee will be charged once the purchase is closed. That fee is 7% of the full and final price of the purchase.<p />
                You must provide all equipment and software necessary to connect to the Service and services, including but not limited to, a mobile device that is suitable to connect with and use Service and services, in cases where the Service offers a mobile component. You are solely responsible for any fees, including Internet connection or mobile fees, that you incur when accessing the Service or services.<p />
                Notwithstanding anything to the contrary in these Terms, the Service and Content may include software components provided by NFT on Demand or its affiliates or a third party that are subject to separate license terms, in which case those license terms will govern such software components. For example, when you click to get more details about any of the Crypto Assets sold through our marketplace, you will notice a third party link to the website from which such Crypto Asset originated. Such website may include license terms governing the use of such Crypto Asset. In the event you purchase such Crypto Asset through our marketplace, you are required to comply with such terms.<p />
                As stated above, your participation in the Auction is also subject to the rules available on this page, Rules.<p />
                Ownership<p />
                Unless otherwise indicated in writing by us, the Service and all content and other materials contained therein, including, without limitation, the NFT on Demand logo and all designs, text, graphics, pictures, information, data, software, sound files, other files and the selection and arrangement thereof (collectively, “Content”) are the proprietary property of NFT on Demand or our affiliates, licensors or users, as applicable.<p />
                Notwithstanding anything to the contrary in these Terms, the Service and Content may include software components provided by NFT on Demand or its affiliates or a third party that are subject to separate license terms, in which case those license terms will govern such software components.<p />
                The NFT on Demand logo and any NFT on Demand product or service names, logos or slogans that may appear on the Service or Service are trademarks of NFT on Demand or our affiliates and may not be copied, imitated or used, in whole or in part, without our prior written permission. You may not use any metatags or other “hidden text” utilizing “NFT on Demand” or any other name, trademark or product or service name of NFT on Demand or our affiliates without our prior written permission. In addition, the look and feel of the Service and Content, including, without limitation, all page headers, custom graphics, button icons and scripts, constitute the service mark, trademark or trade dress of NFT on Demand and may not be copied, imitated or used, in whole or in part, without our prior written permission. All other trademarks, registered trademarks, product names and NFT on Demand names or logos mentioned on the Service are the property of their respective owners and may not be copied, imitated or used, in whole or in part, without the permission of the applicable trademark holder. Reference to any products, services, processes or other information by name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation by NFT on Demand.<p />
                License to Access and Use Our Service and Content<p />
                You are hereby granted a limited, nonexclusive, nontransferable, nonsublicensable, and personal license to access and use the Service and Content; provided, however, that such license is subject to these Terms and does not include any right to (a) sell, resell or use commercially the Service or Content, (b) distribute, publicly perform or publicly display any Content, (c) modify or otherwise make any derivative uses of the Service or Content, or any portion thereof, (d) use any data mining, robots or similar data gathering or extraction methods, (e) download (other than page caching) any portion of the Service or Content, except as expressly permitted by us, and (f) use the Service or Content other than for their intended purposes.<p />
                Hyperlinks<p />
                You are granted a limited, nonexclusive, nontransferable right to create a text hyperlink to the Service for noncommercial purposes, provided that such link does not portray NFT on Demand or our affiliates or any of our products or services in a false, misleading, derogatory or otherwise defamatory manner, and provided further that the linking site does not contain any adult or illegal material or any material that is offensive, harassing or otherwise objectionable. This limited right may be revoked at any time. You may not use a logo or other proprietary graphic of NFT on Demand to link to the Service or Content without our express written permission. Further, you may not use, frame or utilize framing techniques to enclose any NFT on Demand trademark, logo or other proprietary information, including the images found on the Service, the content of any text or the layout or design of any page, or form contained on a page, on the Service without our express written consent.<p />
                Third Party Services<p />
                The Service may contain links to third-party websites (“Third-Party Websites”) and applications (“Third-Party Applications”). When you click on a link to a Third-Party Website or Third-Party Application, we will not warn you that you have left our Service and are subject to the Terms and conditions (including privacy policies) of another website or destination. Such Third-Party Websites and Third-Party Applications are not under the control of NFT on Demand. NFT on Demand is not responsible for any Third-Party Websites or Third-Party Applications. NFT on Demand provides these Third-Party Websites and Third-Party Applications only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Websites or Third-Party Applications, or their products or services. You use all links in Third-Party Websites, and Third-Party Applications at your own risk. When you leave our Service, our Terms and policies no longer govern. You should review all applicable agreements and policies, including privacy and data gathering practices, of any Third-Party Websites or Third-Party Applications, and should make whatever investigation you feel necessary or appropriate before proceeding with any transaction with any third party.<p />
                User Conduct<p />
                You agree that you will not violate any law, contract, intellectual property or other third party right, and that you are solely responsible for your conduct, while accessing or using the Service or participating in the Auction. You agree that you will abide by these Terms and will not:<p />
                Provide false or misleading information to NFT on Demand;<p />
                Use or attempt to use another user’s Account without authorization from such user and NFT on Demand;<p />
                Create or list counterfeit items;<p />
                Pose as another person or create a misleading username;<p />
                Use the Service in any manner that could interfere with, disrupt, negatively affect or inhibit other users from fully enjoying the Service, or that could damage, disable, overburden or impair the functioning of the Service in any manner;<p />
                Develop, utilize, or disseminate any software, or interact with any API in any manner, that could damage, harm, or impair the Service;<p />
                Reverse engineer any aspect of the Service, or do anything that might discover source code or bypass or circumvent measures employed to prevent or limit access to any Service, area or code of the Service;<p />
                Attempt to circumvent any content-filtering techniques we employ, or attempt to access any feature or area of the Service that you are not authorized to access;<p />
                Use any robot, spider, crawler, scraper, script, browser extension, offline reader or other automated means or interface not authorized by us to access the Service, extract data or otherwise interfere with or modify the rendering of Service pages or functionality;<p />
                Use data collected from our Service to contact individuals, companies, or other persons or entities;<p />
                Use data collected from our Service for any direct marketing activity (including without limitation, email marketing, SMS marketing, telemarketing, and direct marketing);<p />
                Bypass or ignore instructions that control all automated access to the Service;<p />
                Use the Service for any illegal or unauthorized purpose, or engage in, encourage or promote any activity that violates these Terms;<p />
                Use the Ethereum Platform to carry out any illegal activities, including but not limited to money laundering, terrorist financing or deliberately engaging in activities designed to adversely affect the performance of the Ethereum Platform, or the Service;<p />
                Engage in wash trading or other deceptive or manipulative trading activities;<p />
                Place misleading bids or offers;<p />
                Spam listings for the purpose of causing a listing to appear at the top of the search results;<p />
                Engage in behaviors that have the intention or the effect of artificially increasing view counts, favorites, volume, or other metrics that NFT on Demand might use to sort search results;<p />
                Use the Service to carry out any financial activities subject to registration or licensing, including but not limited to creating, listing, or buying securities, commodities, options, real estate, or debt instruments;<p />
                Use the Service from a country sanctioned by the government of the United States; or<p />
                Use the Service to participate in fundraising for a business, protocol, or platform, including but not limited to creating, listing, or buying assets that are redeemable for financial instruments, assets that give owners rights to participate in an ICO or any securities offering, or assets that entitle owners to financial rewards, including but not limited to, DeFi yield bonuses, staking bonuses, and burn discounts.<p />
                NFT on Demand facilitates trade among a diverse community of buyers and sellers. Openness is one of our most prized values, and we're committed to providing a platform for the exchange of a wide range of content, including controversial content. These policies ensure that our marketplace offers the widest selection of assets possible while promoting trust and respect, as well as adherence to the law.<p />
                NFT on Demand has always exercised judgment in allowing or disallowing certain assets, listings, smart contracts, and collections consistent with the spirit of openness in a worldwide community of users of a radical new technology. We carefully consider the complete situation and all its details in light of our policies before deciding to remove inappropriate assets, listings, smart contracts, and collections when we discover them or they're brought to our attention.<p />
                Assets, listings, smart contracts, and collections that NFT on Demand deems inappropriate, disruptive, or illegal are prohibited on NFT on Demand. NFT on Demand reserves the rights to determine the appropriateness of listings on its site and remove any listing at any time. If you create or offer an asset, listing, smart contract, or collection in violation of these policies, we will take corrective actions, as appropriate, including but not limited to removing the asset, listing, smart contract, or collection, deleting your NFT on Demand account, and permanently withholding referral payments and developer revenue sharing fees. NFT on Demand cannot destroy or impound your assets or smart contracts, but we reserve the right to destroy inappropriate metadata stored on our servers.<p />
                Assets, listings, smart contracts, and collections that include metadata that violates international or United States intellectual property laws, promotes suicide or self-harm, incites hate or violence against others, degrades or doxes another individual, depicts minors in sexually suggestive situations, or is otherwise illegal in the United States are prohibited on NFT on Demand and will be removed.<p />
                Assets, listings, smart contracts, and collections with a primary or substantial purpose in a game or application that violates international or United States intellectual property laws, promotes suicide or self-harm, incites hate or violence against others, degrades or doxes another individual, depicts minors in sexually suggestive situations, or is otherwise illegal in the United States are prohibited on NFT on Demand and will be removed.<p />
                Assets, listings, smart contracts, and collections created or used primarily or substantially for the purpose of raising funds for the known terrorist organizations listed on https://www.state.gov/foreign-terrorist-organizations/ are prohibited on NFT on Demand and will be removed.<p />
                The sale of stolen assets, converted assets, fraudulently obtained assets, assets taken without authorization, and other illegally obtained assets on NFT on Demand is prohibited. Listing illegally obtained assets may result in your listings being cancelled, your assets being hidden, or your account being suspended.<p />
                If you have reason to believe that an asset listed on NFT on Demand was illegally obtained, please contact us immediately at victor.blankit@gmail.com Include the asset's ID, the asset's contract address, and evidence demonstrating that the asset was illegally obtained. NFT on Demand will review your claim and reply within 72 hours. If we determine from the evidence that the asset is stolen, we will hide it or disable trading of it.<p />
                We require all users to be 18 years old or older. If you are under 18, you may use a parent or guardian's NFT on Demand account, but only with the involvement of the account holder. However, the account holder is responsible for everything done with that account.<p />
                NSFW content is meant for people who are 18 years and older. We allow the sale of this content, but it is subject to being marked NSFW and handled differently than non-NSFW content in navigation menus and search results. Asset names, listings and their descriptions, smart contract names, and collections including profanity or overtly sexual content are prohibited on NFT on Demand and will be removed. A smart contract that contains NSFW content is subject to being marked NSFW, even if the NSFW content only represents a portion of the content on the smart contract.<p />
                Do not create or list illegal or offensive content, such as products that depict graphic sexual acts and images that depict children under the age of 18 in a sexually suggestive manner. Do not use profanity or graphic language in any content you list or create on NFT on Demand.<p />
                Bottom line about NSFW content: it's permitted on NFT on Demand, but we're going to do our best to keep it out of the high traffic areas and if it's extreme in any way, we'll probably remove it.<p />
                If you become aware of the creation, listing, or buying of assets in violation of any of the terms specified in this section, you shall contact us to report it. Creators bear special responsibility for informing NFT on Demand of the existence of their collections, contracts, and assets that violate these terms.<p />
                User Information and Copyright<p />
                You are solely responsible for your use of the Services and for any User Information you provide, including compliance with applicable laws, rules, and regulations. We take no responsibility for the User Information posted or listed via the Services.<p />
                You retain your rights to any User Information you submit, post, or display using the Services.<p />
                By submitting, posting or displaying User Information on or through the Services, you grant us a worldwide, non-exclusive, sublicensable, royalty-free license to use, copy, modify, and display any text, content, files, communications, comments, feedback, suggestions, ideas, concepts, questions, data or other content that you submit or post on or through the Services or through tools or applications we provide for posting or sharing such content (collectively “User Information”) for our lawful business purposes, including to provide, promote, and improve the Services.<p />
                NFT on Demand does not claim that submitting, posting or displaying User Information on or through the Services gives NFT on Demand any ownership or resale rights in your User Information. We're not saying we own it or will resell it. We're just saying we might show it off a bit.<p />
                You represent and warrant that you have, or have obtained, all rights, licenses, consents, permissions, power and/or authority necessary to grant the rights granted herein for any User Information that you submit, post or display on or through the Services. You agree that such User Information will not contain material subject to copyright or other proprietary rights, unless you have necessary permission or are otherwise legally entitled to post the material and to grant NFT on Demand the license described above.<p />
                NFT on Demand reserves the right to remove content without prior notice. NFT on Demand will take down works in response to formal infringement claims and will terminate a user's access to the Services if the user is determined to be a repeat infringer.<p />
                If you believe that your content has been copied in a way that constitutes copyright infringement, please report this by contacting our agents, we will support you.<p />
                Your claims regarding content on the Services must include:<p />
                A written communication delivered to the NFT on Demand Personnel<p />
                A physical or electronic signature of someone authorized to act on behalf of the copyright owner;<p />
                Identification of the copyrighted work(s) allegedly infringed;<p />
                Identification of material claimed to be infringing, reasonably sufficient to permit Company to locate the material;<p />
                Information reasonably sufficient to permit the Company to contact the complaining party. This can be an address, phone number, email address, or other suitable method of contact;<p />
                A statement that the “complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent or the law; and”<p />
                A statement that the information in the notice is accurate and, under penalty of perjury, that the complaining party is authorized to act on behalf of the copyright owner.<p />
                If you believe that your likeness has been used in a way that violates your personality rights, please report this by contacting our agents.<p />
                <p />
                <p />
                Formal claims regarding content on the Services must include:<p />
                A written communication delivered to the NFT on Demand Personnel.<p />
                A physical or electronic signature of someone authorized to act on behalf of the person or the estate affected;<p />
                Identification of material claimed to be violating, reasonably sufficient to permit Company to locate the material;<p />
                Information reasonably sufficient to permit the Company to contact the complaining party. This can be an address, phone number, email address, or other suitable method of contact;<p />
                A statement that the “complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the person or the estate affected, its agent or the law; and”<p />
                A statement that the information in the notice is accurate and, under penalty of perjury, that the complaining party is authorized to act on behalf of the person or the estate.<p />
                Indemnification<p />
                To the fullest extent permitted by applicable law, you agree to indemnify, defend and hold harmless NFT on Demand, and our respective past, present and future employees, officers, directors, contractors, consultants, equity holders, suppliers, vendors, service providers, parent companies, subsidiaries, affiliates, agents, representatives, predecessors, successors and assigns (individually and collectively, the “NFT on Demand Parties”), from and against all actual or alleged third party claims, damages, awards, judgments, losses, liabilities, obligations, penalties, interest, fees, expenses (including, without limitation, attorneys’ fees and expenses) and costs (including, without limitation, court costs, costs of settlement and costs of pursuing indemnification and insurance), of every kind and nature whatsoever, whether known or unknown, foreseen or unforeseen, matured or unmatured, or suspected or unsuspected, in law or equity, whether in tort, contract or otherwise (collectively, “Claims”), including, but not limited to, damages to property or personal injury, that are caused by, arise out of or are related to (a) your use or misuse of the Service, User Information or Crypto Assets, (b) any feedback you provide, (c) your violation of these Terms, and (d) your violation of the rights of a third party, including another user or MetaMask. You agree to promptly notify NFT on Demand of any third party Claims and cooperate with the NFT on Demand Parties in defending such Claims. You further agree that the NFT on Demand Parties shall have control of the defense or settlement of any third party Claims. THIS INDEMNITY IS IN ADDITION TO, AND NOT IN LIEU OF, ANY OTHER INDEMNITIES SET FORTH IN A WRITTEN AGREEMENT BETWEEN YOU AND NFT on Demand.<p />
                Disclaimers<p />
                EXCEPT AS EXPRESSLY PROVIDED TO THE CONTRARY IN A WRITING BY NFT on Demand, THE SERVICE, CONTENT CONTAINED THEREIN, AND CRYPTO ASSETS LISTED THEREIN ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED. NFT on Demand (AND ITS SUPPLIERS) MAKE NO WARRANTY THAT THE SERVICE: (A) WILL MEET YOUR REQUIREMENTS; (B) WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; OR (C) WILL BE ACCURATE, RELIABLE, COMPLETE, LEGAL, OR SAFE. NFT on Demand DISCLAIMS ALL OTHER WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT AS TO THE SERVICE, CONTENT CONTAINED THEREIN. NFT on Demand DOES NOT REPRESENT OR WARRANT THAT CONTENT ON THE SERVICE IS ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE. WE WILL NOT BE LIABLE FOR ANY LOSS OF ANY KIND FROM ANY ACTION TAKEN OR TAKEN IN RELIANCE ON MATERIAL OR INFORMATION, CONTAINED ON THE SERVICE. WHILE NFT on Demand ATTEMPTS TO MAKE YOUR ACCESS TO AND USE OF THE SERVICE AND CONTENT SAFE, NFT on Demand CANNOT AND DOES NOT REPRESENT OR WARRANT THAT THE SERVICE, CONTENT, ANY CRYPTO ASSETS LISTED ON OUR SERVICE OR OUR SERVERS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE CANNOT GUARANTEE THE SECURITY OF ANY DATA THAT YOU DISCLOSE ONLINE. YOU ACCEPT THE INHERENT SECURITY RISKS OF PROVIDING INFORMATION AND DEALING ONLINE OVER THE INTERNET AND WILL NOT HOLD US RESPONSIBLE FOR ANY BREACH OF SECURITY UNLESS IT IS DUE TO OUR GROSS NEGLIGENCE.<p />
                WE WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSS AND TAKE NO RESPONSIBILITY FOR, AND WILL NOT BE LIABLE TO YOU FOR, ANY USE OF CRYPTO ASSETS, INCLUDING BUT NOT LIMITED TO ANY LOSSES, DAMAGES OR CLAIMS ARISING FROM: (A) USER ERROR SUCH AS FORGOTTEN PASSWORDS, INCORRECTLY CONSTRUCTED TRANSACTIONS, OR MISTYPED ADDRESSES; (B) SERVER FAILURE OR DATA LOSS; (C) CORRUPTED WALLET FILES; (D) UNAUTHORIZED ACCESS TO APPLICATIONS; (E) ANY UNAUTHORIZED THIRD PARTY ACTIVITIES, INCLUDING WITHOUT LIMITATION THE USE OF VIRUSES, PHISHING, BRUTEFORCING OR OTHER MEANS OF ATTACK AGAINST THE SERVICE OR CRYPTO ASSETS.<p />
                CRYPTO ASSETS ARE INTANGIBLE DIGITAL ASSETS. THEY EXIST ONLY BY VIRTUE OF THE OWNERSHIP RECORD MAINTAINED IN THE ETHEREUM NETWORK. ANY TRANSFER OF TITLE THAT MIGHT OCCUR IN ANY UNIQUE DIGITAL ASSET OCCURS ON THE DECENTRALIZED LEDGER WITHIN THE ETHEREUM PLATFORM. WE DO NOT GUARANTEE THAT NFT on Demand OR ANY NFT on Demand PARTY CAN EFFECT THE TRANSFER OF TITLE OR RIGHT IN ANY CRYPTO ASSETS.<p />
                NFT on Demand is not responsible for sustained casualties due to vulnerability or any kind of failure, abnormal behavior of software (e.g., wallet, smart contract), blockchains or any other features of the Crypto Assets. NFT on Demand is not responsible for casualties due to late reports by developers or representatives (or no report at all) of any issues with the blockchain supporting Crypto Assets including forks, technical node issues or any other issues having fund losses as a result.<p />
                Nothing in these Terms shall exclude or limit liability of either party for fraud, death or bodily injury caused by negligence, violation of laws, or any other activity that cannot be limited or excluded by legitimate means.<p />
                SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES IN CONTRACTS WITH CONSUMERS, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU.<p />
                Assumption of Risk<p />
                You accept and acknowledge:<p />
                The prices of blockchain assets are extremely volatile. Fluctuations in the price of other digital assets could materially and adversely affect the Crypto Assets, which may also be subject to significant price volatility. We cannot guarantee that any purchasers of Crypto Assets will not lose money.<p />
                You are solely responsible for determining what, if any, taxes apply to your Crypto Assets transactions. Neither NFT on Demand nor any other NFT on Demand Party is responsible for determining the taxes that apply to Crypto Assets transactions.<p />
                Our Service does not store, send, or receive Crypto Assets. This is because Crypto Assets exist only by virtue of the ownership record maintained on its supporting blockchain. Any transfer of Crypto Assets occurs within the supporting blockchain and not on this Service.<p />
                There are risks associated with using an Internet based currency, including but not limited to, the risk of hardware, software and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to information stored within your wallet. You accept and acknowledge that NFT on Demand will not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience when using the Crypto Assets, however caused.<p />
                A lack of use or public interest in the creation and development of distributed ecosystems could negatively impact the development of those ecosystems and related applications, and could therefore also negatively impact the potential utility or value of Crypto Assets.<p />
                The regulatory regime governing blockchain technologies, cryptocurrencies, and tokens is uncertain, and new regulations or policies may materially adversely affect the development of the Auction and/or Service and the utility of Crypto Assets.<p />
                The Service will rely on third-party platforms such as MetaMask to perform the transactions for the Auction of Crypto Assets. If we are unable to maintain a good relationship with such platform providers; if the terms and conditions or pricing of such platform providers change; if we violate or cannot comply with the terms and conditions of such platforms; or if any of such platforms loses market share or falls out of favor or is unavailable for a prolonged period of time, access to and use of the Service will suffer.<p />
                There are risks associated with purchasing user generated content, including but not limited to, the risk of purchasing counterfeit assets, mislabeled assets, assets that are vulnerable to metadata decay, assets on smart contracts with bugs, and assets that may become untransferable. NFT on Demand reserves the right to hide collections, contracts, and assets affected by any of these issues or by other issues. Assets you purchase may become inaccessible on NFT on Demand. Under no circumstances shall the inability to view your assets on NFT on Demand serve as grounds for a claim against NFT on Demand.<p />
                Limitation of Liability<p />
                TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT WILL NFT on Demand BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFIT OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES ARISING FROM THESE TERMS, THE SERVICE, PRODUCTS OR THIRD PARTY SITES AND PRODUCTS, OR FOR ANY DAMAGES RELATED TO LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, OR LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE, EVEN IF FORESEEABLE AND EVEN IF NFT on Demand HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ACCESS TO, AND USE OF, THE SERVICES, PRODUCTS OR THIRD PARTY SITES AND PRODUCTS ARE AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA RESULTING THEREFROM.<p />
                NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, IN NO EVENT SHALL THE MAXIMUM AGGREGATE LIABILITY OF NFT on Demand ARISING OUT OF OR IN ANY WAY RELATED TO THESE TERMS, THE ACCESS TO AND USE OF THE SERVICE, CONTENT, CRYPTO ASSETS, OR ANY PRODUCTS OR SERVICES PURCHASED ON THE SERVICE EXCEED THE GREATER OF (A) $100 OR (B) THE AMOUNT RECEIVED BY NFT on Demand FROM THE SALE OF CRYPTO ASSETS THAT ARE THE SUBJECT OF THE CLAIM.<p />
                THE FOREGOING LIMITATIONS OF LIABILITY SHALL NOT APPLY TO LIABILITY OF NFT on Demand FOR (A) DEATH OR PERSONAL INJURY CAUSED BY A MEMBER OF NFT on Demand’S NEGLIGENCE; OR FOR (B) ANY INJURY CAUSED BY A MEMBER OF NFT on Demand’S FRAUD OR FRAUDULENT MISREPRESENTATION<p />
                Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you. Some jurisdictions also limit disclaimers or limitations of liability for personal injury from consumer products, so this limitation may not apply to personal injury claims.<p />
                Modifications to the Service<p />
                We reserve the right in our sole discretion to modify, suspend or discontinue, temporarily or permanently, the Services (or any features or parts thereof) or suspend or discontinue the Auction at any time and without liability therefore.<p />
                Dispute Resolution; Arbitration.<p />
                Dispute Resolution. Please read the following arbitration agreement in this Section (“Arbitration Agreement”) carefully. It requires you to arbitrate disputes with NFT on Demand and limits the manner in which you can seek relief from us.<p />
                Applicability of Arbitration Agreement. You agree that any dispute or claim relating in any way to your access or use of the Service, to any products sold or distributed through the Service, or to any aspect of your relationship with NFT on Demand, will be resolved by binding arbitration, rather than in court, except that (1) you may assert claims in small claims court if your claims qualify; and (2) you or NFT on Demand may seek equitable relief in court for infringement or other misuse of intellectual property rights (such as trademarks, trade dress, domain names, trade secrets, copyrights, and patents).<p />
                Arbitration Rules and Forum. The Federal Arbitration Act governs the interpretation and enforcement of this Arbitration Agreement. To begin an arbitration proceeding, you must send a letter requesting arbitration and describing your claim to our registered agent Luis Eduardo Arevalo Oliver.  The arbitration will be conducted by JAMS, an established alternative dispute resolution provider. Disputes involving claims and counterclaims under $250,000, not inclusive of attorneys’ fees and interest, shall be subject to JAMS’s most current version of the Streamlined Arbitration Rules and procedures available at http://www.jamsadr.com/rules-streamlined-arbitration/; all other claims shall be subject to JAMS’s most current version of the Comprehensive Arbitration Rules and Procedures, available at http://www.jamsadr.com/rules-comprehensive-arbitration/. JAMS’s rules are also available at jamsadr.com or by calling JAMS at 800-352- 5267. If JAMS is not available to arbitrate, the parties will select an alternative arbitral forum. If the arbitrator finds that you cannot afford to pay JAMS’s filing, administrative, hearing and/or other fees and cannot obtain a waiver from JAMS, NFT on Demand will pay them for you. In addition, NFT on Demand will reimburse all such JAMS’s filing, administrative, hearing and/or other fees for claims totaling less than $10,000 unless the arbitrator determines the claims are frivolous. You may choose to have the arbitration conducted by telephone, based on written submissions, or in person in the country where you live or at another mutually agreed location. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.<p />
                Authority of Arbitrator. The arbitrator shall have exclusive authority to (a) determine the scope and enforceability of this Arbitration Agreement and (b) resolve any dispute related to the interpretation, applicability, enforceability or formation of this Arbitration Agreement including, but not limited to any claim that all or any part of this Arbitration Agreement is void or voidable. The arbitration will decide the rights and liabilities, if any, of you and NFT on Demand. The arbitration proceeding will not be consolidated with any other matters or joined with any other cases or parties. The arbitrator shall have the authority to grant motions dispositive of all or part of any claim. The arbitrator shall have the authority to award monetary damages and to grant any non- monetary remedy or relief available to an individual under applicable law, the arbitral forum’s rules, and the Terms (including the Arbitration Agreement). The arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded. The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have. The award of the arbitrator is final and binding upon you and us.<p />
                Waiver of Jury Trial. YOU AND NFT on Demand HEREBY WAIVE ANY CONSTITUTIONAL AND STATUTORY RIGHTS TO SUE IN COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY. You and NFT on Demand are instead electing that all claims and disputes shall be resolved by arbitration under this Arbitration Agreement, except as specified in Section 15(b) above. An arbitrator can award on an individual basis the same damages and relief as a court and must follow these Terms as a court would. However, there is no judge or jury in arbitration, and court review of an arbitration award is subject to very limited review.<p />
                Waiver of Class or Other Non-Individualized Relief. ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED ON AN INDIVIDUAL BASIS AND NOT ON A OR COLLECTIVE CLASS BASIS, ONLY INDIVIDUAL RELIEF IS AVAILABLE, AND CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER. If a decision is issued stating that applicable law precludes enforcement of any part of this subsection’s limitations as to a given claim for relief, then that claim must be severed from the arbitration and brought in the state or federal courts located in the State of Delaware. in case of US users or Mexican Court in case of Mexican Users. All other claims shall be arbitrated.<p />
                30-Day Right to Opt Out. You have the right to opt out of the provisions of this Arbitration Agreement by sending written notice of your decision to opt out to the following address: Villa Fruela 58 Col. DEsarrollo Urbano Quetzalcoatl CDMX Mexico City Mexico within 30 days after first becoming subject to this Arbitration Agreement. You may also submit your decision to any of the contacts of NFT on Demand. Your notice must include your name and address, the email address you used to set up your account (if you have one), and an unequivocal statement that you want to opt out of this Arbitration Agreement. If you opt out of this Arbitration Agreement, all other parts of these Terms will continue to apply to you. Opting out of this Arbitration Agreement has no effect on any other arbitration agreements that you may currently have, or may enter in the future, with us.<p />
                Severability. Except as provided in this Section, if any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable, then such specific part or parts shall be of no force and effect and shall be severed and the remainder of the Arbitration Agreement shall continue in full force and effect.<p />
                Survival of Agreement. This Arbitration Agreement will survive the termination of your relationship with NFT on Demand.<p />
                Modification. Notwithstanding any provision in these Terms to the contrary, we agree that if NFT on Demand makes any future material change to this Arbitration Agreement, you may reject that change within thirty (30) days of such change becoming effective by writing to NFT on Demand at the following address: Villa Fruela 58 Col. DEsarrollo Urbano Quetzalcoatl CDMX Mexico City Mexico<p />
                Governing Law and Venue These Terms, your access to and use of the Service and Content, and your participation in the Auction shall be governed by and construed and enforced in accordance with the laws of the State of California, without regard to conflict of law rules or principles of the State of California, or any other jurisdiction) that would cause the application of the laws of any other jurisdiction that would cause the application of the laws of any other jurisdiction. Any dispute between the parties that is not subject to arbitration or cannot be heard in small claims court, shall be resolved in the state or federal courts of San Francisco County in the State of California, and the United States, respectively, sitting in the State of California.<p />
                Termination Notwithstanding anything contained in these Terms, we reserve the right, without notice and in our sole discretion, to terminate your right to access or use the Service at any time and for any or no reason, and you acknowledge and agree that we shall have no liability or obligation to you in such event and that you will not be entitled to a refund of any amounts that you have already paid to us, to the fullest extent permitted by applicable law.<p />
                Severability If any term, clause or provision of these Terms is held invalid or unenforceable, then that term, clause or provision will be severable from these Terms and will not affect the validity or enforceability of any remaining part of that term, clause or provision, or any other term, clause or provision of these Terms.<p />
                Survival The following sections will survive the expiration or termination of these Terms and the termination of your Account: all defined terms and Sections 1-4 and 7-19.<p />
                Miscellaneous These Terms along with the Auction Rules constitute the entire agreement between you and NFT on Demand relating to your access to and use of the Services and Content, and your participation in the Auction. These Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you without the prior written consent of NFT on Demand prior, concurrent or subsequent circumstance, and NFT on Demand’s failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision. Except as otherwise provided herein, these Terms are intended solely for the benefit of the parties and are not intended to confer third party beneficiary rights upon any other person or entity.<p />
                END OF AGREEMENT<p />
            </div>
        );
    }
}

export default Terms;